name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
      - name: Restaurar dependencies
        run: dotnet restore
        working-directory: ./backend/
      - name: Build
        run: dotnet build 
        working-directory: ./backend/
      - name: Test
        run: dotnet test 
        working-directory: ./backend/
      - name: sonarscan-dotnet
        uses: highbyte/sonarscan-dotnet@v2.2.3
        


